services:
  mcp-server:
    build: .
    cap_drop:
      - all
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    environment:
      - BRAVE_API_KEY
      - BRAVE_MCP_TRANSPORT=http
      - BRAVE_MCP_PORT=8080
      - BRAVE_MCP_HOST=0.0.0.0
      - BRAVE_MCP_LOG_LEVEL=info
    init: true
    ports:
      - 8080:8080
    security_opt:
      - no-new-privileges:true
