name: Build Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm install

      - name: Bump patch version
        id: bump-version
        run: |
          VERSION=$(npm version patch --no-git-tag-version)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build assets
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${GITHUB_REPOSITORY}:${{ steps.bump-version.outputs.version }} \
            -t ${GITHUB_REPOSITORY}:${GITHUB_SHA} \
            -t ${GITHUB_REPOSITORY}:${GITHUB_SHA::7} \
            -t ${GITHUB_REPOSITORY}:latest \
            .

      - name: Push to Docker Hub
        run: docker push ${GITHUB_REPOSITORY} --all-tags

      - name: Bump version and commit build assets
        run: |
          git add package.json package-lock.json
          git commit -m "ci: update build assets (${{ steps.bump-version.outputs.version }})"
          git push

      - name: Publish NPM package
        run: npm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          tag_name: ${{ steps.bump-version.outputs.version }}
          generate_release_notes: true
          make_latest: true
